### ISSUE TITLE
Mini Connected

### ISSUE THREAD

**Issue by Minims** [m1n3rva/bimmer_connected#1]
Hi, 

Is there a way to get Mini Fix series status ? 
Those cars use Mini Connected App. 
It may use quite the same things to get Data,  No ? 

Thx

**Comment by ChristianKuehnel** [comment]
I guess the BMW and Mini navigation systems are quite similar. Can you please test the status.py program in this library? Then we should see if that works as well...

**Comment by Minims** [comment]
My VIN is not recognized i think. I have this issue on connectedDrive website. (Not a BMW)

```
DEBUG:requests.packages.urllib3.connectionpool:https://www.bmw-connecteddrive.fr:443 "GET /api/vehicle/dynamic/v1/WMWLN71000*******HTTP/1.1" 400 None
Traceback (most recent call last):
  File "status.py", line 29, in <module>
    main()
  File "status.py", line 22, in main
    bimmer.update_data()
  File "/home/pi/github/bimmer_connected/bimmer_connected/__init__.py", line 102, in update_data
    raise IOError('Unknown status code {}'.format(response.status_code))
OSError: Unknown status code 400

```

**Comment by ChristianKuehnel** [comment]
That might be more difficult than I expected: For the BMWs we're using the BMW Connected Drive portal. But for MINI I did not find such a portal. Not sure how we can then access the data without such a portal...

**Comment by ChristianKuehnel** [comment]
@Minims can you figure out the url, the Mini Connected app is talking to?

**Comment by Minims** [comment]
I don't really know.
I saw a call to 46.137.104.93:443 , 40.68.210.104:443 , 40.114.241.141:443 when I tcpdump &  login to the app.

I saw some dns resolution to : b2vapi.bmwgroup.com (160.46.245.252) , myc-profile.bmwgroup.com (40.68.210.104), myc-profile.bmwusa.com (104.43.142.33). I hope it may help.

**Comment by Minims** [comment]
I can connect, but no vehicle found :-/.

```
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): b2vapi.bmwgroup.com
DEBUG:requests.packages.urllib3.connectionpool:https://b2vapi.bmwgroup.com:443 "GET /webapi/v1/user/vehicles HTTP/1.1" 200 None
Found 0 vehicles: 
```

**Comment by ChristianKuehnel** [comment]
So the user authentication is working, that's step number one :smile: 

I did not find another known URL for the Mini servers on the web. Right now it's probably a trial-and-error approch to find the right address. And I can't do it, as I do not have a Mini.

Just to be sure we're looking in the right place: Can you remote control your mini from your MINI Connected app (e.g. locating the car, locking, unlocking)?

**Comment by m1n3rva** [comment]
Just had a look at the MINI Connected app :iphone: but I could not identify any useful urls :crying_cat_face:

**Comment by Minims** [comment]
I can have, fuel level, how many kms the car has, and the location. That’s all.

**Comment by edwork** [comment]
Update:

I setup the bimmer_connected component normally for my 2019 Mini (in home-assistant) - all of the expected sensors have loaded and I've got a lock component loaded too.

**Comment by m1n3rva** [comment]
That's great to hear 👍 ! I'll update the description of the Library accordingly.

@gerard33, you can also advertise this in Home Assistant 😄
