### ISSUE TITLE
Get data with active Check Control messages

### ISSUE THREAD

**Issue by m1n3rva** [m1n3rva/bimmer_connected#55]
At the moment we do not have any example data with active check control messages. So we cannot parse these :sob: 

If you have a vehicle :car: that currently shows check control messages (red :exclamation: or yellow :warning:  warnings in your instrument cluster :clock12: :clock630: : ). Please send us your data:
https://github.com/ChristianKuehnel/bimmer_connected#data-contributions

The `status.json` should then contain some data in the field `checkControlMessages`.

**Comment by robbz23** [comment]
I have a white exclamation right now for tire pressure after changing all 4 this weekend but it didn't generate a check control message.  sorry.

**Comment by gerard33** [comment]
I would have expected a message from that as in the app for my car the only check control messages are for tyre pressure and motor oil :neutral_face:

My tyres are also changed last week, but that didn't produce an message.
So I guess we have to wait a bit longer :wink:

**Comment by gerard33** [comment]
@m1n3rva I have some data finally :wink:

```
"checkControlMessages": [
      {
        "ccmDescriptionLong": "You can continue driving. Check tyre pressure when tyres are cold and adjust if necessary. Perform reset after adjustment. See Owner's Handbook for further information.",
        "ccmDescriptionShort": "Tyre pressure notification",
        "ccmId": 955,
        "ccmMileage": 41544
      }
    ]
```

My suggestion is to show the `ccmDescriptionShort` on the HA card like in the screenshot below.
I have now changed this is in the binary_sensor component of HA on my test version.

But the cleanest way would be to do the processing in the library of course. Can you spend some time to implement that?

![cbs_screenshot](https://user-images.githubusercontent.com/11230573/45980675-e795b700-c052-11e8-9577-d3c00fc50899.jpg)

**Comment by gerard33** [comment]
Hi @m1n3rva,

I will make a PR to bump the version of bimmer_connected to `0.5.3` and will make a small change in the HA code of the binary sensor to support the `check_control_messages` as well.

Current code
```py
elif self._attribute == 'check_control_messages':
    check_control_messages = vehicle_state.check_control_messages
    if not check_control_messages:
        result['check_control_messages'] = 'OK'
    else:
        result['check_control_messages'] = check_control_messages
```

New code
```py
elif self._attribute == 'check_control_messages':
    check_control_messages = vehicle_state.check_control_messages
    if not check_control_messages:
        result['check_control_messages'] = 'OK'
    else:
        cbs_list = []
        for message in check_control_messages:
            cbs_list.append(message['ccmDescriptionShort'])
        result['check_control_messages'] = cbs_list
```

**Comment by m1n3rva** [comment]
@gerard33 Thx for the data :scroll:!

I created 2 PRs for this:
* in #90 I just added your data and created tests for CCMs
* in #91 I also added a new API to parse these CCMs into Python objects. I guess this does not fit to your implementation in Home Assistant.

Please let me know what you think of #91 and if we should merge that.

**Comment by gerard33** [comment]
@m1n3rva thanks for the update.
Will do some test for #91 as it's much nicer to have this data parsed in `bimmer_connected` just as the rest.
Don't think this will be a breaking change. If that's confirmed I can update the code in HA and bump the version.

**Comment by gerard33** [comment]
@m1n3rva you can merge #91 and place a new version on Pypi.
I have tested this and will make a HA PR so this data is parsed just as the `cbs` part.
This won't be a breaking change as the current value will be remained and I will add some extra info.

![screenshot_2](https://user-images.githubusercontent.com/11230573/47118045-69e65500-d266-11e8-92b1-ded033215818.jpg)

**Comment by gerard33** [comment]
Hmm, I did some more thinking and it is possible that you can get multiple `check_control_messages` at the same time. I know that at least messages for tyre pressure and motor oil are possible.

That's way we need to group the messages, I used the `id` for that. It will look like this.
Will mean that this is a breaking change for the attribute, but that's no real issue.

@m1n3rva what do you think?

![screenshot_3](https://user-images.githubusercontent.com/11230573/47119007-99e32780-d269-11e8-9571-e4848c901138.jpg)
