### ISSUE TITLE
HASS sensors - implement conversion to imperial units

### ISSUE THREAD

**Issue by m1n3rva** [m1n3rva/bimmer_connected#56]
see https://community.home-assistant.io/t/bmw-connecteddrive-component/39569/200?u=m1n3rva

**Comment by uchagani** [comment]
I've updated the bmw component in HASS: https://github.com/home-assistant/home-assistant/pull/17197

**Comment by uchagani** [comment]
@m1n3rva just FYI the above PR has been merged into HA and should be in the next release.

**Comment by m1n3rva** [comment]
cool thx 🎆
