### ISSUE TITLE
2016 BMW 2-series Active Tourer (F45)

### ISSUE THREAD

**Issue by PaskoMoto** [m1n3rva/bimmer_connected#60]
[vehicles_0.txt](https://github.com/ChristianKuehnel/bimmer_connected/files/1853176/vehicles_0.txt)
[status_0.txt](https://github.com/ChristianKuehnel/bimmer_connected/files/1853177/status_0.txt)

**Comment by m1n3rva** [comment]
Hey @PaskoMoto ,

thx for your data :spiral_notepad:!

The contents of you status_0.txt is quite short compared to the other examples that we have, e.g. https://github.com/m1n3rva/bimmer_connected/blob/master/test/responses/G31_NBTevo/status.json

If this as the data was provided from the tool? Or did you shorten it somehow?

**Comment by PaskoMoto** [comment]
Hi.
No, I didn't strip the results. I suspect I got less information due to not having a smartphone associated via USB hub in the car.
I can recall getting more results when a smartphone was associated with the vehicle.
Do you think this makes sense?
Anyway I'm planning to associate a new device and retry a new association to see if I can retrieve more data. :)
Sorry for late answer.
Regards.

**Comment by m1n3rva** [comment]
Thx @PaskoMoto for your data :heart: 

Does the app show much about the state of your vehicle? I guess you can only trigger the remote services of the vehicle. Correct?

**Comment by PaskoMoto** [comment]
Hi.
Indeed yesterday I installed a new version of the Connected app (without being in the car) and it 'triggered' some new things in the responses I got from your app. Here are the results. They now include location and technical info of the car...
[status_0.txt](https://github.com/m1n3rva/bimmer_connected/files/1886234/status_0.txt)
[vehicles_0.txt](https://github.com/m1n3rva/bimmer_connected/files/1886235/vehicles_0.txt)

Also I will connect an app-enabled smartphone to the car tomorrow and see this still adds more info :-)
Regards.

**Comment by m1n3rva** [comment]
@PaskoMoto thx for the update. I also updated the test data for the vehicle.

The only change I've seen is that new we have a position on your vehicle.
