### ISSUE TITLE
BMW 225xe

### ISSUE THREAD

**Issue by vasaru** [m1n3rva/bimmer_connected#64]
In the Connected drive app I have values for the last trip driven. Is it possible to get these from the API as well? 

Values that would be nice are 
Total distance
Electric distance driven
Consumption
Duration
From (location)
To (location)

Thanks

[bmw_225xe.zip](https://github.com/m1n3rva/bimmer_connected/files/1889201/bmw_225xe.zip)

**Comment by m1n3rva** [comment]
@vasaru looking at the code here, this seems to be quite straight forward :yum: 
https://github.com/edent/BMW-i-Remote#get-last-trip

I'll give it a shot :dart:

**Comment by m1n3rva** [comment]
@vasaru did you give it a try?

**Comment by m1n3rva** [comment]
no feedback for a long time -> closing the ticket
