### ISSUE TITLE
BMW CarData

### ISSUE THREAD

**Issue by dgomes** [m1n3rva/bimmer_connected#75]
AFAIK this implementation uses the portal API's

Currently some countries already have CarData (https://www.bmw-connecteddrive.de/app/index.html#/portal/cardata-intern)

As any one tried to create a CarData account? Were you successful ?

**Comment by m1n3rva** [comment]
Yes I did: it gives you a one-time snapshot of your vehicle data. And it took several hours to give it my data set. So this is not useful if you want to know what BMW has stores about your vehicle, but it's not useful to get live data...

**Comment by dgomes** [comment]
The method for owners is as you described (asked for myself) but for developers its supposed to be realtime. You do need to register with BMW, I registered on friday and still waiting...

https://aos.bmwgroup.com/web/oss/registration

**Comment by m1n3rva** [comment]
I also tried to register but I got the answer that they only support commercial entities who are already some  BMW customer. Which does not match our use case...

**Comment by dgomes** [comment]
Still waiting.... guess they take some time 🗡 

Hope someone over there changes his mind, else this library will periodically break as seen this week.
