### ISSUE TITLE
Location Update

### ISSUE THREAD

**Issue by PaskoMoto** [m1n3rva/bimmer_connected#76]
Hi.
I was wondering whether it is already known how to trigger a vehicle location update (while it is stationary) as you would do with the Android/iOS app, provided that the option is enabled in the vehicle.

Firstly I have tried something like this:

`GET https://www.bmw-connecteddrive.xy/api/vehicle/service/v1/-----VIN_NUMBER ---- `

This returns a list of 'features' including the already known: RDL, RDU, RCN, RHB, RLF, RCT.... but also returns something called "VF" which I interpreted as Vehicle_Finder.

But if  I try use POST to trigger this function (it already works OK with RDL for instance) I get the following status_report: CDP_ERROR.

Does anyone know if I am missing some parameter (maybe sender location or something like that) or the appropriate syntax to trigger the location update?.

Thanks in advance.

**Comment by m1n3rva** [comment]
I don't really know, I did not use this feature so far. But there is a remote service available:
https://github.com/edent/BMW-i-Remote/blob/master/README.md#vehicle-finder

But I have no idea what that really does, so I did not implement it. 

And as the vehicle automatically sends it's postion to the server on engine shut off, I did not really need it...

**Comment by PaskoMoto** [comment]
Hi.
Thanks for your answer. I guess I'll have to park it elsewhere to see if the location info returned by the API is updated. :)
Regards.
