### ISSUE TITLE
Errors related to electric car in log since 0.5.2 for combustion engine only car

### ISSUE THREAD

**Issue by gerard33** [m1n3rva/bimmer_connected#86]
Hi @m1n3rva I have a lot of warnings related to an electric car in the log since using 0.5.2.

As I don't have an electric car this is strange of course :wink:
Can you have a look at this? Is this something that needs to be changed in the library or should I have a look at the HA component?

And as intermediate solution maybe good to implement PR #83 so these items are not written as errors in the log.

```
No data available for attribute <function VehicleState.charging_status at 0x7f8cf9f7d7b8>!
13:10 deps/lib/python3.6/site-packages/bimmer_connected/state.py (ERROR)
No data available for attribute <function VehicleState.charging_status at 0x7f8cf9f7d7b8>!
13:10 deps/lib/python3.6/site-packages/bimmer_connected/state.py (ERROR)
No data available for attribute <function VehicleState.charging_status at 0x7f8cf9f7d7b8>!
13:10 deps/lib/python3.6/site-packages/bimmer_connected/state.py (ERROR)
No data available for attribute <function VehicleState.charging_status at 0x7f8cf9f7d7b8>!
13:10 deps/lib/python3.6/site-packages/bimmer_connected/state.py (ERROR)
No data available for attribute <function VehicleState.remaining_range_electric at 0x7f8cf9f7d488>!
13:10 deps/lib/python3.6/site-packages/bimmer_connected/state.py (ERROR)
```

**Comment by m1n3rva** [comment]
Hi @gerard33 ,

I was thinking about your PR for some time and I see 2 possibile directions to go:

1. Quick fix: just hide the errors in the log file. This is easy to do and will probably solve the issue

2. Do it properly: Figure out, why HASS is trying to read sensor data that is not available for your vehicle. Figure out which data is available for your vehicle and then only use the data that is available for a specific type of vehicle. This is probably quite some work as we need to make sure we can predict which vehicle will provide which data. Maybe something has changed in the backend...

So far I was going for option 2, especially the property  `vehicle.available_attributes`  was intended for exactly this purpose: Get a list of the available data and then only display this.
https://github.com/m1n3rva/bimmer_connected/blob/db3b76d31808a4e96186cff72da18b82f0c11b57/bimmer_connected/vehicle.py#L129

But this does obviously not work as you're getting error messages on missing data. And I do not have to much time right now to spend on improving the library and doing further investigations.

That being said, I would go for option 1.
What do you think?

**Comment by gerard33** [comment]
Hi @m1n3rva,

I would go for option 1 as well. I have already done this in my forked version and that works fine.
There is also this issue https://github.com/home-assistant/home-assistant/issues/16631 that will be solved as well.

When we have more time on our hands we can dive into this and find the actual root cause. And maybe also some other items which are still on the to do list :grinning:

But for know changing the log level will be the right solution. If you can update the library on Pypi then I will make a PR for HA to bump the version.

**Comment by m1n3rva** [comment]
New release is out...
